// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: greet.proto

// Protobuf Java Version: 3.25.3
package com.xaaef.grpc.lib.pb;

public final class Greet {
  private Greet() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xaaef_HelloRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xaaef_HelloRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xaaef_HelloReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xaaef_HelloReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xaaef_HelloReply_MessageEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xaaef_HelloReply_MessageEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013greet.proto\022\tcom.xaaef\"\034\n\014HelloRequest" +
      "\022\014\n\004name\030\001 \001(\t\"q\n\nHelloReply\0223\n\007message\030" +
      "\001 \003(\0132\".com.xaaef.HelloReply.MessageEntr" +
      "y\032.\n\014MessageEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030" +
      "\002 \001(\t:\0028\0012G\n\007Greeter\022<\n\010SayHello\022\027.com.x" +
      "aaef.HelloRequest\032\025.com.xaaef.HelloReply" +
      "\"\000B4\n\025com.xaaef.grpc.lib.pbP\001Z\n./pb;gree" +
      "t\252\002\014GrpcService1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_xaaef_HelloRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_xaaef_HelloRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xaaef_HelloRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_com_xaaef_HelloReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_xaaef_HelloReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xaaef_HelloReply_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_com_xaaef_HelloReply_MessageEntry_descriptor =
      internal_static_com_xaaef_HelloReply_descriptor.getNestedTypes().get(0);
    internal_static_com_xaaef_HelloReply_MessageEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xaaef_HelloReply_MessageEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
