// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: greet.proto

// Protobuf Java Version: 3.25.3
package com.xaaef.grpc.lib.pb;

public interface HelloReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.xaaef.HelloReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>map&lt;string, string&gt; message = 1;</code>
   */
  int getMessageCount();
  /**
   * <code>map&lt;string, string&gt; message = 1;</code>
   */
  boolean containsMessage(
      java.lang.String key);
  /**
   * Use {@link #getMessageMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getMessage();
  /**
   * <code>map&lt;string, string&gt; message = 1;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getMessageMap();
  /**
   * <code>map&lt;string, string&gt; message = 1;</code>
   */
  /* nullable */
java.lang.String getMessageOrDefault(
      java.lang.String key,
      /* nullable */
java.lang.String defaultValue);
  /**
   * <code>map&lt;string, string&gt; message = 1;</code>
   */
  java.lang.String getMessageOrThrow(
      java.lang.String key);
}
