### http sayHello
GET http://{{baseHost}}/rest/hello?name=tom
Content-Type: application/json
Host: k8s.example.com


### istio server http sayHello
GET http://{{baseHost}}/server/hello?name=tom1
Content-Type: application/json
Host: k8s.example.com


### istio client http sayHello
GET http://{{baseHost}}/rest/hello?name=tom1
Content-Type: application/json
Host: k8s.example.com


### istio client grpc sayHello
GET http://{{baseHost}}/grpc/hello?name=tom1
Content-Type: application/json
Host: k8s.example.com


